"""Константы проекта."""

ME = "profile"

# User
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
MAX_LENGTH_MIDDLE_NAME = 150
MAX_LENGTH_POSITION = 150
MAX_LENGTH_EMAIL_ADDRESS = 254
MAX_LENGTH_ROLE = 10
MAX_LENGTH_PHONE = 12
MAX_LENGTH_FACE_DESCRIPTOR = 128
MAX_LENGTH_PASSWORD = 128
MAX_LENGTH_TELEGRAM_CHAT_ID = 200

MAX_LENGTH_INSTRUCTION_TYPE = 100
MAX_LENGTH_INSTRUCTION = 100
MAX_LENGTH_MEDIA_NAME = 100
MAX_LENGTH_PASSING_SCORE = 100
MIN_LENGTH_PASSING_SCORE = 1
MAX_LENGTH_TYPE_QUESTION = 20
MAX_LENGTH_BADGE = 100
MAX_LENGTH_RANK = 100
MAX_NOTIFICATION_TYPE = 100
MAX_NOTIFICATION_ERROR = 100
MAX_NAME_SHIFT = 100

# CELERY_BEAT_SCHEDULE
MORNING_HOUR = 7
MORNING_MINUTE = 45

DAY_HOUR = 15
DAY_MINUTE = 45

EVENING_HOUR = 23
EVENING_MINUTE = 45

GAME_HOUR = 7
GAME_MINUTE = 0
LIMIT_GAME_SWIPER_QUESTIONS = 60

INSTRUCTION_SCORE = 10
TEST_SCORE = 10

POWER_OF_USER = 8
