"""Константы проекта."""

ME = 'profile'

# User
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
MAX_LENGTH_MIDDLE_NAME = 150
MAX_LENGTH_POSITION = 150
MAX_LENGTH_EMAIL_ADDRESS = 254
MAX_LENGTH_ROLE = 10
MAX_LENGTH_PHONE = 12
MAX_LENGTH_FACE_DESCRIPTOR = 128
MAX_LENGTH_PASSWORD = 128

MAX_LENGTH_INSTRUCTION_TYPE = 100
MAX_LENGTH_INSTRUCTION = 100
MAX_LENGTH_MEDIA_NAME = 100
MAX_LENGTH_PASSING_SCORE = 100
MIN_LENGTH_PASSING_SCORE = 1
