"""Константы проекта."""

ME = 'me'

# User
MAX_LENGTH_FIRST_NAME = 150
MAX_LENGTH_LAST_NAME = 150
MAX_LENGTH_MIDDLE_NAME = 150
MAX_LENGTH_POSITION = 150
MAX_LENGTH_EMAIL_ADDRESS = 254
MAX_LENGTH_ROLE = 10

MAX_LENGTH_INSTRUCTION_TYPE = 100
MAX_LENGTH_INSTRUCTION = 100
MAX_LENGTH_MEDIA_NAME = 100