# Generated by Django 4.2 on 2025-03-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="middle_name",
            field=models.CharField(max_length=150, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="user",
            name="mobile_phone",
            field=models.CharField(
                max_length=12, unique=True, verbose_name="Мобильный телефон"
            ),
        ),
    ]
