# Generated by Django 4.2 on 2025-03-23 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_alter_instructionagreement_attention_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="instructionagreement",
            name="user",
        ),
    ]
