# Generated by Django 4.2 on 2025-03-24 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_instruction_instruction_agreement'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'photo_data',
                    models.TextField(
                        verbose_name='Массив данных фото пользователя'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'user',
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='publickey',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='Пользователь',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Массив данных',
                'verbose_name_plural': 'Массивы данных',
            },
        ),
        migrations.DeleteModel(
            name='Publickey',
        ),
    ]
