# Generated by Django 4.2 on 2025-03-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_answer_answer_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='tests',
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='questions',
                to='api.tests',
                verbose_name='Тест',
            ),
            preserve_default=False,
        ),
    ]
