# Generated by Django 4.2 on 2025-03-25 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_remove_tests_question_question_tests'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='face_descriptor',
            field=models.TextField(
                blank=True, null=True, verbose_name='Дескриптор лица'
            ),
        ),
        migrations.DeleteModel(
            name='PhotoData',
        ),
    ]
