# Generated by Django 4.2 on 2025-03-25 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_user_created_at_user_face_descriptor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthday",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата рождения"
            ),
        ),
    ]
