# Generated by Django 4.2 on 2025-03-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0013_referencelink_question_explanation_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="question",
            name="reference_links",
        ),
        migrations.AddField(
            model_name="referencelink",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referenceLinks",
                to="api.question",
                verbose_name="Вопрос",
            ),
        ),
    ]
