# Generated by Django 4.2 on 2025-03-25 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0015_alter_referencelink_question"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="referencelink",
            options={
                "verbose_name": "Ссылка на объяснение",
                "verbose_name_plural": "Ссылки на объяснение",
            },
        ),
        migrations.AlterField(
            model_name="referencelink",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referenceLinks",
                to="api.question",
                verbose_name="Вопрос",
            ),
        ),
    ]
