# Generated by Django 4.2 on 2025-03-25 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0016_alter_referencelink_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencelink",
            name="question",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="referenceLinks",
                to="api.question",
                verbose_name="Вопрос",
            ),
        ),
    ]
