# Generated by Django 4.2 on 2025-03-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_referencelink_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referencelink',
            name='question',
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='reference_link',
                to='api.question',
                verbose_name='Вопрос',
            ),
        ),
    ]
