# Generated by Django 4.2 on 2025-03-25 11:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_remove_instructionagreement_attention_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="answer",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="answers",
                to="api.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.RemoveField(
            model_name="instruction",
            name="instruction_agreement",
        ),
        migrations.AlterField(
            model_name="instruction",
            name="type_of_instruction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instructions",
                to="api.typeofinstruction",
                verbose_name="Тип инструктажа",
            ),
        ),
        migrations.AlterField(
            model_name="instructionresult",
            name="instruction",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instruction_results",
                to="api.instruction",
                verbose_name="Инструктаж",
            ),
        ),
        migrations.AlterField(
            model_name="instructionresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instruction_results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="tests",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="api.tests",
                verbose_name="Тест",
            ),
        ),
        migrations.AlterField(
            model_name="referencelink",
            name="question",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reference_link",
                to="api.question",
                verbose_name="Вопрос",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="test",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_results",
                to="api.tests",
                verbose_name="Тест",
            ),
        ),
        migrations.AlterField(
            model_name="testresult",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="test_results",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
        migrations.AddField(
            model_name="instruction",
            name="instruction_agreement",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="instruction",
                to="api.instructionagreement",
                verbose_name="Согласие на инструктаж",
            ),
        ),
    ]
