# Generated by Django 4.2 on 2025-03-25 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_answer_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.URLField(
                blank=True, null=True, verbose_name='Изображение'
            ),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(
                blank=True, default='', verbose_name='Объяснение'
            ),
        ),
    ]
