# Generated by Django 4.2 on 2025-03-26 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0021_question_image_alter_question_explanation"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="testresult",
            options={
                "ordering": ("-date",),
                "verbose_name": "Результат тестирования",
                "verbose_name_plural": "Результаты тестирования",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=128, verbose_name="Пароль"),
        ),
    ]
