# Generated by Django 4.2 on 2025-03-26 19:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alter_user_password"),
    ]

    operations = [
        migrations.AddField(
            model_name="testresult",
            name="mark",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Оценка",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="tests",
            name="passing_score",
            field=models.IntegerField(
                validators=[
                    django.core.validators.MinValueValidator(10),
                    django.core.validators.MaxValueValidator(10),
                ],
                verbose_name="Проходной балл",
            ),
        ),
    ]
