# Generated by Django 4.2 on 2025-04-02 15:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_video_delete_media'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='date',
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2025,
                    4,
                    2,
                    15,
                    57,
                    15,
                    773363,
                    tzinfo=datetime.timezone.utc,
                ),
                verbose_name='Дата загрузки',
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(
                blank=True, upload_to='media/videos/', verbose_name='Видеофайл'
            ),
        ),
    ]
