# Generated by Django 4.2 on 2025-04-02 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_video_date_alter_video_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='face_descriptor',
            field=models.TextField(
                blank=True,
                null=True,
                unique=True,
                verbose_name='Дескриптор лица',
            ),
        ),
    ]
