# Generated by Django 4.2 on 2025-04-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "api",
            "0032_alter_testresult_options_remove_testresult_date_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="NormativeLegislation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Название")),
                (
                    "description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание"
                    ),
                ),
                (
                    "url",
                    models.URLField(blank=True, null=True, verbose_name="URL"),
                ),
                (
                    "date",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата загрузки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Нормативно-правовой акт",
                "verbose_name_plural": "Нормативно-правовые акты",
            },
        ),
    ]
