# Generated by Django 4.2 on 2025-04-05 17:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0033_normativelegislation"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="points",
            field=models.IntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Количество баллов за вопрос",
            ),
            preserve_default=False,
        ),
    ]
