# Generated by Django 4.2 on 2025-04-05 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_question_points"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tests",
            name="total_points",
        ),
    ]
