# Generated by Django 4.2 on 2025-04-05 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_remove_tests_total_points"),
    ]

    operations = [
        migrations.CreateModel(
            name="InstructionAgreementResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("agreement_type", models.CharField(max_length=50)),
                ("agreed", models.BooleanField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "instruction_result",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="agreement_results",
                        to="api.instructionresult",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат согласия инструктажа",
                "verbose_name_plural": "Результаты согласий инструктажа",
            },
        ),
    ]
