# Generated by Django 4.2 on 2025-04-06 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_instructionagreementresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testresult",
            name="mark",
            field=models.FloatField(
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="Оценка",
            ),
        ),
    ]
