# Generated by Django 4.2 on 2025-04-07 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_alter_testresult_mark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="mobile_phone",
            field=models.CharField(
                blank=True,
                max_length=12,
                null=True,
                unique=True,
                verbose_name="Мобильный телефон",
            ),
        ),
    ]
