# Generated by Django 4.2 on 2025-04-07 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_alter_user_mobile_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="normativelegislation",
            name="file",
            field=models.FileField(
                blank=True, upload_to="media/nlas/", verbose_name="НПА"
            ),
        ),
    ]
