# Generated by Django 4.2 on 2025-04-07 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_normativelegislation_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="referencelink",
            name="url",
            field=models.TextField(verbose_name="Источник"),
        ),
    ]
