# Generated by Django 4.2 on 2025-04-07 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_alter_referencelink_url"),
    ]

    operations = [
        migrations.RenameField(
            model_name="referencelink",
            old_name="url",
            new_name="source",
        ),
    ]
