# Generated by Django 4.2 on 2025-04-09 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_user_supervisor_user_telegram_chat_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="error",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="Ошибка отправки",
            ),
        ),
    ]
