# Generated by Django 4.2 on 2025-04-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_shift_dutyschedule"),
    ]

    operations = [
        migrations.AlterField(
            model_name="normativelegislation",
            name="file",
            field=models.FileField(
                blank=True, upload_to="nlas/", verbose_name="НПА"
            ),
        ),
        migrations.AlterField(
            model_name="video",
            name="file",
            field=models.FileField(
                blank=True, upload_to="videos/", verbose_name="Видеофайл"
            ),
        ),
    ]
