# Generated by Django 4.2 on 2025-04-11 15:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alter_normativelegislation_file_alter_video_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="Badge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("instruction", "За инструктажи"),
                            ("test", "За тесты"),
                            ("department", "Профессиональные"),
                        ],
                        max_length=20,
                        verbose_name="Тип значка",
                    ),
                ),
                ("icon", models.ImageField(upload_to="badges/", verbose_name="Иконка")),
                (
                    "required_count",
                    models.IntegerField(default=1, verbose_name="Требуемое количество"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("icon", models.CharField(max_length=5, verbose_name="Иконка-эмодзи")),
            ],
        ),
        migrations.CreateModel(
            name="Rank",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="Название")),
                ("required_points", models.IntegerField(verbose_name="Требуемые очки")),
                ("icon", models.ImageField(upload_to="ranks/", verbose_name="Иконка")),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="experience_points",
            field=models.IntegerField(default=0, verbose_name="Очки опыта"),
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "awarded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата получения"
                    ),
                ),
                (
                    "badge",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.badge"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="badge",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.department",
                verbose_name="Цех/отдел",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="current_rank",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.rank",
                verbose_name="Текущее звание",
            ),
        ),
    ]
