# Generated by Django 4.2 on 2025-04-11 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_badge_department_rank_user_experience_points_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="badge",
            options={"verbose_name": "Значок", "verbose_name_plural": "Значки"},
        ),
        migrations.AlterModelOptions(
            name="rank",
            options={"verbose_name": "Звание", "verbose_name_plural": "Звания"},
        ),
        migrations.AlterModelOptions(
            name="userbadge",
            options={
                "verbose_name": "Значок пользователя",
                "verbose_name_plural": "Значки пользователей",
            },
        ),
        migrations.RemoveField(
            model_name="badge",
            name="department",
        ),
        migrations.AddField(
            model_name="badge",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.position",
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="position",
            name="icon",
            field=models.ImageField(
                blank=True, null=True, upload_to="positions/", verbose_name="Иконка"
            ),
        ),
        migrations.DeleteModel(
            name="Department",
        ),
    ]
