# Generated by Django 4.2 on 2025-04-12 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0048_alter_badge_options_alter_rank_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rank",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="api.position",
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="badge",
            name="required_count",
            field=models.IntegerField(
                default=1, verbose_name="Требуемое количество очков"
            ),
        ),
    ]
