# Generated by Django 4.2 on 2025-04-12 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0049_rank_position_alter_badge_required_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="badge",
            name="badge_type",
        ),
        migrations.AlterField(
            model_name="badge",
            name="icon",
            field=models.ImageField(
                blank=True, upload_to="badges/", verbose_name="Иконка"
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="icon",
            field=models.ImageField(
                blank=True, upload_to="ranks/", verbose_name="Иконка"
            ),
        ),
    ]
