# Generated by Django 4.2 on 2025-04-12 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0050_remove_badge_badge_type_alter_badge_icon_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="instruction",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="instructions",
                to="api.position",
                verbose_name="Должность",
            ),
        ),
        migrations.AddField(
            model_name="tests",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tests",
                to="api.position",
                verbose_name="Должность",
            ),
        ),
        migrations.AlterField(
            model_name="instruction",
            name="instruction_agreement",
            field=models.ManyToManyField(
                blank=True,
                related_name="instruction",
                to="api.instructionagreement",
                verbose_name="Согласие на инструктаж",
            ),
        ),
    ]
