# Generated by Django 4.2 on 2025-04-13 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_instruction_position_tests_position_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="position",
            name="icon",
            field=models.ImageField(
                blank=True,
                default="positions/default.png",
                null=True,
                upload_to="positions/",
                verbose_name="Иконка",
            ),
        ),
    ]
