# Generated by Django 4.2 on 2025-05-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_alter_position_icon"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="testresult",
            name="test_duration",
        ),
    ]
