# Generated by Django 4.2 on 2025-05-03 11:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_remove_testresult_test_duration"),
    ]

    operations = [
        migrations.CreateModel(
            name="GameSwiperResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True, verbose_name="Дата игры")),
                ("score", models.IntegerField(default=0, verbose_name="Очки")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="game_swiper_results",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Результат игры Swiper",
                "verbose_name_plural": "Результаты игры Swiper",
            },
        ),
        migrations.CreateModel(
            name="GameSwiper",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "question",
                    models.TextField(blank=True, null=True, verbose_name="Вопрос"),
                ),
                ("answer", models.BooleanField(verbose_name="Ответ")),
                (
                    "position",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="game_swipers",
                        to="api.position",
                        verbose_name="Должность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Игра Swiper",
                "verbose_name_plural": "Игры Swiper",
            },
        ),
    ]
