# Generated by Django 4.2 on 2025-05-03 20:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0054_gameswiperresult_gameswiper"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="error",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Ошибка отправки"
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("test", "Результат теста"),
                    ("instruction", "Результат инструктажа"),
                ],
                max_length=100,
                verbose_name="Тип уведомления",
            ),
        ),
        migrations.AlterField(
            model_name="rank",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="shift",
            name="name",
            field=models.CharField(max_length=100, verbose_name="Название смены"),
        ),
        migrations.AlterField(
            model_name="user",
            name="telegram_chat_id",
            field=models.CharField(
                blank=True, max_length=200, null=True, verbose_name="Telegram Chat ID"
            ),
        ),
        migrations.CreateModel(
            name="PowerOfUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("power", models.IntegerField(default=0, verbose_name="МегаСила")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="power_of_user",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Сила пользователя",
                "verbose_name_plural": "Сила пользователей",
            },
        ),
    ]
