# Generated by Django 4.2 on 2025-05-05 18:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0057_alter_powerofuser_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="powerofuser",
            name="power",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(8),
                ],
                verbose_name="МегаСила",
            ),
        ),
    ]
