# Generated by Django 5.2.1 on 2025-05-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_alter_powerofuser_power"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_badges",
                to="api.badge",
            ),
        ),
    ]
