# Generated by Django 5.2.1 on 2025-05-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_alter_userbadge_badge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userbadge",
            name="badge",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.badge"
            ),
        ),
    ]
