# Generated by Django 5.2.1 on 2025-05-08 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0060_alter_userbadge_badge"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tests",
            name="test_is_control",
            field=models.BooleanField(
                db_index=True, verbose_name="Тест является контрольным"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                db_index=True,
                max_length=254,
                unique=True,
                verbose_name="Электронная почта",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="experience_points",
            field=models.IntegerField(
                db_index=True, default=0, verbose_name="Очки опыта"
            ),
        ),
    ]
