# Generated by Django 5.2.1 on 2025-05-15 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_quizresult"),
    ]

    operations = [
        migrations.CreateModel(
            name="Quiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("instruction", models.TextField(verbose_name="Инструкция")),
            ],
            options={
                "verbose_name": "Квиз",
                "verbose_name_plural": "Квизы",
            },
        ),
        migrations.AddField(
            model_name="quizresult",
            name="level",
            field=models.IntegerField(default=1, verbose_name="Уровень"),
        ),
    ]
