# Generated by Django 5.2.1 on 2025-05-15 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0063_quiz_quizresult_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="level",
            field=models.IntegerField(default=1, verbose_name="Уровень"),
        ),
    ]
