# Generated by Django 5.2.1 on 2025-05-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_quiz_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="instruction",
            field=models.JSONField(verbose_name="Инструкция"),
        ),
    ]
