# Generated by Django 5.2.1 on 2025-05-20 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0065_alter_quiz_instruction"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Quiz",
            new_name="FireSafetyQuiz",
        ),
    ]
