# Generated by Django 5.2.1 on 2025-05-20 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0066_rename_quiz_firesafetyquiz"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicineQuiz",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(verbose_name="Название")),
                ("type", models.IntegerField(default=1, verbose_name="Тип")),
            ],
            options={
                "verbose_name": "Медицинский квиз",
                "verbose_name_plural": "Медицинские квизы",
            },
        ),
        migrations.CreateModel(
            name="MedicineQuizItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item", models.TextField(verbose_name="Действие")),
                (
                    "serial_number",
                    models.IntegerField(default=1, verbose_name="Порядковый номер"),
                ),
                (
                    "quiz",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="quiz_items",
                        to="api.medicinequiz",
                        verbose_name="Медицинский кивз",
                    ),
                ),
            ],
            options={
                "verbose_name": "Действие для медицинского квиза",
                "verbose_name_plural": "Действия для медицинского квиза",
            },
        ),
    ]
