# Generated by Django 5.2.1 on 2025-05-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0067_medicinequiz_medicinequizitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicinequizitem",
            old_name="item",
            new_name="text",
        ),
    ]
